sudo: false
language: generic

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: false
      addons:
        apt:
          packages:
            - make
            - guile
            - chezscheme
  fast_finish: true

before_script:
  - bin/fetch-configlet
  - bin/configlet lint .

script:
  - make ci
