sudo: false
language: generic

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: false
      addons:
        apt:
          packages:
            - guile-2.2
            - chezscheme
  fast_finish: true

script:
  - make ci
