sudo: false
language: generic

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: false
      addons:
        apt:
          packages:
            - guile-2.0
  fast_finish: true

before_script:
  - bin/fetch-configlet
  - bin/configlet lint .

script:
  - bin/run-tests.sh
