#+TITLE: Exercism Scheme Track
#+AUTHOR: Jason Lewis

[[https://gitter.im/exercism/xscheme][https://badges.gitter.im/Join%20Chat.svg]]
[[https://travis-ci.org/exercism/scheme][https://travis-ci.org/exercism/scheme.svg?branch=master]]

Exercisms in scheme.

** Overview
 
   Scheme tooling for testing and implementing problems is in the [[https://github.com/exercism/scheme/tree/master/code][code]]
   directory. 
     - [[https://github.com/exercism/scheme/tree/master/code/json.sls][code/json.sls]] and [[https://github.com/exercism/scheme/tree/master/code/packrat.sls][code/packrat.sls]] take care of JSON
       serialization, allowing for track development and testing from
       within scheme.
     - [[https://github.com/exercism/scheme/tree/master/code/outils.ss][code/outils.ss]] has various utility procedures.
     - [[https://github.com/exercism/scheme/tree/master/code/test.ss][code/test.ss]] is a bare bones test library that gets spliced to
       the generated test files.
     - [[https://github.com/exercism/scheme/tree/master/code/track.ss][code/track.ss]] contains the rest of it.

** Setup
   To work on the scheme track you'll want [[https://cisco.github.io/ChezScheme/][ChezScheme]] installed. The
   json serialization library in =code/json.sls= relies on some
   modules from the [[https://github.com/fedeinthemix/chez-srfi][srfi]] collection, whose path needs to be visible to
   scheme via the =CHEZSCHEMELIBDIRS= environment
   variable. Instructions for installing the srfi collection can be
   found at [[https://github.com/fedeinthemix/chez-srfi/blob/master/srfi/INSTALL.chez][srfi/INSTALL.chez]].

   It is assumed that the [[https://github.com/exercism/problem-specifications][exercism/problem-specifications]] can be found
   in the same directory that this track is. If not, running =make=
   will clone it there. =make= will also ensure that the =configlet=
   binary is in the =bin= directory, for formatting the =config.json=,
   linting the exercises, and generating fresh uuids for exercises.

** Contributing

   Please see [[https://github.com/exercism/scheme/blob/master/CONTRIBUTING.org][contributing]].

** Dependencies

   Scheme specific dependencies include [[https://cisco.github.io/ChezScheme/][ChezScheme]] and [[https://github.com/fedeinthemix/chez-srfi][chez-srfi]].

** Scheme icon

   The Scheme logo was created by https://en.wikipedia.org/wiki/User:Matthias.f
 and released under the Creative Commons Attribution-Share Alike 3.0 Unported license.
 We adapted the logo, creating a pink/black version to use on Exercism.
