; These tests are auto-generated with test data from: 
; https://github.com/exercism/problem-specifications/blob/main/exercises/bob/canonical-data.json
; File last updated on 2026-10-10T19:43:26+00:00

(load "test-util.ss")

(define test-cases
  `(
    (test-success "1. asking a question"  equal? response-for '("Does this cryogenic chamber make me look fat?") 
        "Sure.")
    (test-success "2. shouting"  equal? response-for '("WATCH OUT!") 
        "Whoa, chill out!")
    (test-success "3. forceful question"  equal? response-for '("WHAT'S GOING ON?") 
        "Calm down, I know what I'm doing!")
    (test-success "4. silence"  equal? response-for '("") 
        "Fine. Be that way!")
    (test-success "5. stating something"  equal? response-for '("Tom-ay-to, tom-aaaah-to.") 
        "Whatever.")
    (test-success "6. asking a numeric question"  equal? response-for '("You are, what, like 15?") 
        "Sure.")
    (test-success "7. asking gibberish"  equal? response-for '("fffbbcbeab?") 
        "Sure.")
    (test-success "8. question with no letters"  equal? response-for '("4?") 
        "Sure.")
    (test-success "9. non-letters with question"  equal? response-for '(":) ?") 
        "Sure.")
    (test-success "10. prattling on"  equal? response-for '("Wait! Hang on. Are you going to be OK?") 
        "Sure.")
    (test-success "11. ending with whitespace"  equal? response-for '("Okay if like my  spacebar  quite a bit?   ") 
        "Sure.")
    (test-success "12. multiple line question"  equal? response-for '("
Does this cryogenic chamber make
 me look fat?") 
        "Sure.")
    (test-success "13. shouting gibberish"  equal? response-for '("FCECDFCAAB") 
        "Whoa, chill out!")
    (test-success "14. shouting a statement containing a question mark"  equal? response-for '("DO LIONS EAT PEOPLE? AHHHHH.") 
        "Whoa, chill out!")
    (test-success "15. shouting numbers"  equal? response-for '("1, 2, 3 GO!") 
        "Whoa, chill out!")
    (test-success "16. shouting with special characters"  equal? response-for '("ZOMG THE %^*@#$(*^ ZOMBIES ARE COMING!!11!!1!") 
        "Whoa, chill out!")
    (test-success "17. shouting with no exclamation mark"  equal? response-for '("I HATE THE DENTIST") 
        "Whoa, chill out!")
    (test-success "18. prolonged silence"  equal? response-for '("          ") 
        "Fine. Be that way!")
    (test-success "19. alternate silence"  equal? response-for '("										") 
        "Fine. Be that way!")
    (test-success "20. other whitespace"  equal? response-for '("
 	") 
        "Fine. Be that way!")
    (test-success "21. talking forcefully"  equal? response-for '("Hi there!") 
        "Whatever.")
    (test-success "22. using acronyms in regular speech"  equal? response-for '("It's OK if you don't want to go work for NASA.") 
        "Whatever.")
    (test-success "23. no letters"  equal? response-for '("1, 2, 3") 
        "Whatever.")
    (test-success "24. statement containing question mark"  equal? response-for '("Ending with ? means a question.") 
        "Whatever.")
    (test-success "25. starting with whitespace"  equal? response-for '("         hmmmmmmm...") 
        "Whatever.")
    (test-success "26. non-question ending with whitespace"  equal? response-for '("This is a statement ending with whitespace      ") 
        "Whatever.")
    ))

(run-with-cli "bob.scm" (list test-cases))
