name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  verify_exercises:
    runs-on: ubuntu-26.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Install Scheme
        run: |
          sudo apt-get update
          sudo apt-get install guile-3.0 chezscheme jq

      - name: Verify all exercises
        run: bin/verify-exercises
