name: scheme / main

on:
  push:
    branches: [master, main]
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Install project dependencies
        run: |
          sudo apt-get update
          sudo apt-get install guile-3.0 chezscheme

      - name: Run exercism/scheme ci (runs tests) for all exercises
        run: make ci
